Sync files from swift-dns/shared (#3)
Co-authored-by: swift-dns-helper[bot] <295214583+swift-dns-helper[bot]@users.noreply.github.com>

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -1,4 +1,4 @@
-name: unit-tests
+name: integration-tests
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
@@ -13,7 +13,7 @@ defaults:
     shell: bash --noprofile --norc -Eeuo pipefail {0}
 
 jobs:
-  linux-unit:
+  linux-integration-tests:
     strategy:
       fail-fast: false
       matrix:
@@ -35,10 +35,13 @@ jobs:
         with:
           persist-credentials: false
 
-      - name: Install zstd for faster caching, and curl for codecov action
+      - name: Install dependencies
         run: |
           apt-get update -y
           apt-get install -y zstd curl
+          if [[ "${{ github.event.repository.name }}" == 'swift-dns' ]]; then
+            apt-get install -y tcpdump
+          fi
 
       - name: Restore .build
         if: ${{ runner.debug != '1' }}
@@ -46,14 +49,13 @@ jobs:
         uses: actions/cache/restore@v5
         with:
           path: .build
-          key: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"
-          restore-keys: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-"
+          key: "${{ github.event.repository.name }}-integration-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"
+          restore-keys: "${{ github.event.repository.name }}-integration-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-"
 
       - name: Build ${{ github.event.repository.name }}
         run: |
           swift build \
             --build-tests \
-            --enable-code-coverage \
             --explicit-target-dependency-import-check error \
             -Xswiftc -require-explicit-sendable \
             -c ${{ matrix.config.mode }}
@@ -63,22 +65,53 @@ jobs:
         uses: actions/cache/save@v5
         with:
           path: .build
-          key: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"
+          key: "${{ github.event.repository.name }}-integration-tests-${{ matrix.config.mode }}-build-${{ matrix.swift-image.name }}-${{ runner.os }}-${{ hashFiles('./Package.resolved') }}"
 
       - name: Run tests
+        id: tests-run
         run: |
+          if [[ "${{ github.event.repository.name }}" == 'swift-dns' ]]; then
+            tcpdump -w dns.pcap 'port 53 and (host 8.8.4.4 or host 240.1.2.3)' &
+            TCPDUMP_PID=$!
+          fi
+
+          # Disable 'set -e' to prevent the script from exiting on non-zero exit codes
+          set +e
           swift test \
-            --skip "IntegrationTests." \
+            --filter "IntegrationTests." \
             --skip-build \
-            --enable-code-coverage \
             -Xswiftc -require-explicit-sendable \
             -c ${{ matrix.config.mode }}
+          echo "exit-status=$?" >> $GITHUB_OUTPUT
+          set -e
 
-      - name: Submit code coverage
-        uses: vapor/swift-codecov-action@v0.3
+          if [[ "${{ github.event.repository.name }}" == 'swift-dns' ]]; then
+            kill $TCPDUMP_PID
+          fi
+
+      - name: Calculate capture file name
+        id: calculate-capture-file-name
+        if: ${{ github.event.repository.name == 'swift-dns' }}
+        run: |
+          RESULT="${{ steps.tests-run.outputs.exit-status == 0 && 'success' || 'failure' }}"
+          TIMESTAMP="$(date -u +"%Y-%m-%d-%H-%M-%S")"
+          SHORT_SHA="$(echo '${{ github.sha }}' | cut -c 1-7)"
+          FILE_NAME="swift-dns_dns_capture_${TIMESTAMP}_${RESULT}_Linux_${{ matrix.swift-image.name }}_${{ matrix.config.mode }}_${SHORT_SHA}"
+          FILE_NAME="${FILE_NAME//:/_}"
+
+          echo "file_name=${FILE_NAME}" >> "${GITHUB_OUTPUT}"
+
+          mv dns.pcap "${FILE_NAME}.pcap"
+
+      - name: Archive packet capture
+        if: ${{ github.event.repository.name == 'swift-dns' }}
+        uses: actions/upload-artifact@v7
         with:
-          build_parameters: "-c ${{ matrix.config.mode }}"
-          codecov_token: "${{ secrets.CODECOV_TOKEN }}"
+          name: "${{ steps.calculate-capture-file-name.outputs.file_name }}"
+          path: "${{ steps.calculate-capture-file-name.outputs.file_name }}.pcap"
+
+      - name: Exit with correct status
+        run: exit ${{ steps.tests-run.outputs.exit-status }}
 
   cache-swiftly-toolchain-for-macos:
     strategy:
@@ -103,7 +136,7 @@ jobs:
         uses: actions/cache/restore@v5
         with:
           path: "${{ env.SWIFTLY_HOME_DIR }}"
-          key: "${{ github.event.repository.name }}-swiftly-home-${{ matrix.swift.version }}-${{ runner.os }}"
+          key: "${{ github.event.repository.name }}-swiftly-home-integration-tests-${{ matrix.swift.version }}-${{ runner.os }}"
 
       - name: Restore swiftly bin
         if: ${{ runner.debug != '1' }}
@@ -111,7 +144,7 @@ jobs:
         uses: actions/cache/restore@v5
         with:
           path: "${{ env.SWIFTLY_BIN_DIR }}"
-          key: "${{ github.event.repository.name }}-swiftly-bin-${{ matrix.swift.version }}-${{ runner.os }}"
+          key: "${{ github.event.repository.name }}-swiftly-bin-integration-tests-${{ matrix.swift.version }}-${{ runner.os }}"
 
       - name: Restore swiftly toolchains
         if: ${{ runner.debug != '1' }}
@@ -119,7 +152,7 @@ jobs:
         uses: actions/cache/restore@v5
         with:
           path: "${{ env.SWIFTLY_TOOLCHAINS_DIR }}"
-          key: "${{ github.event.repository.name }}-swiftly-toolchain-${{ matrix.swift.version }}-${{ runner.os }}"
+          key: "${{ github.event.repository.name }}-swiftly-toolchain-integration-tests-${{ matrix.swift.version }}-${{ runner.os }}"
 
       - name: Update swift via Swiftly
         run: |
@@ -141,23 +174,23 @@ jobs:
         uses: actions/cache/save@v5
         with:
           path: "${{ env.SWIFTLY_HOME_DIR }}"
-          key: "${{ github.event.repository.name }}-swiftly-home-${{ matrix.swift.version }}-${{ runner.os }}"
+          key: "${{ github.event.repository.name }}-swiftly-home-integration-tests-${{ matrix.swift.version }}-${{ runner.os }}"
 
       - name: Cache swiftly bin
         if: steps.restore-bin.outputs.cache-hit != 'true'
         uses: actions/cache/save@v5
         with:
           path: "${{ env.SWIFTLY_BIN_DIR }}"
-          key: "${{ github.event.repository.name }}-swiftly-bin-${{ matrix.swift.version }}-${{ runner.os }}"
+          key: "${{ github.event.repository.name }}-swiftly-bin-integration-tests-${{ matrix.swift.version }}-${{ runner.os }}"
 
       - name: Cache swiftly toolchains
         if: steps.restore-toolchains.outputs.cache-hit != 'true'
         uses: actions/cache/save@v5
         with:
           path: "${{ env.SWIFTLY_TOOLCHAINS_DIR }}"
-          key: "${{ github.event.repository.name }}-swiftly-toolchain-${{ matrix.swift.version }}-${{ runner.os }}"
+          key: "${{ github.event.repository.name }}-swiftly-toolchain-integration-tests-${{ matrix.swift.version }}-${{ runner.os }}"
 
-  macos-unit:
+  macos-integration-tests:
     strategy:
       fail-fast: false
       matrix:
@@ -174,9 +207,9 @@ jobs:
 
     runs-on: ${{ matrix.macos.version }}
 
-    needs: cache-swiftly-toolchain-for-macos
-
     timeout-minutes: 20
+
+    needs: cache-swiftly-toolchain-for-macos
 
     env:
       SWIFTLY_HOME_DIR: "/Users/runner/.swiftly"
@@ -189,6 +222,9 @@ jobs:
         with:
           xcode-version: ${{ matrix.xcode.version }}
 
+      - name: Install tcpdump for packet capture
+        run: brew install tcpdump
+
       - name: Check out ${{ github.event.repository.name }}
         uses: actions/checkout@v7
         with:
@@ -199,21 +235,21 @@ jobs:
         uses: actions/cache/restore@v5
         with:
           path: "${{ env.SWIFTLY_HOME_DIR }}"
-          key: "${{ github.event.repository.name }}-swiftly-home-${{ matrix.swift.version }}-${{ runner.os }}"
+          key: "${{ github.event.repository.name }}-swiftly-home-integration-tests-${{ matrix.swift.version }}-${{ runner.os }}"
 
       - name: Restore swiftly bin
         id: "restore-bin"
         uses: actions/cache/restore@v5
         with:
           path: "${{ env.SWIFTLY_BIN_DIR }}"
-          key: "${{ github.event.repository.name }}-swiftly-bin-${{ matrix.swift.version }}-${{ runner.os }}"
+          key: "${{ github.event.repository.name }}-swiftly-bin-integration-tests-${{ matrix.swift.version }}-${{ runner.os }}"
 
       - name: Restore swiftly toolchains
         id: "restore-toolchains"
         uses: actions/cache/restore@v5
         with:
           path: "${{ env.SWIFTLY_TOOLCHAINS_DIR }}"
-          key: "${{ github.event.repository.name }}-swiftly-toolchain-${{ matrix.swift.version }}-${{ runner.os }}"
+          key: "${{ github.event.repository.name }}-swiftly-toolchain-integration-tests-${{ matrix.swift.version }}-${{ runner.os }}"
 
       - name: Update swift via Swiftly
         run: |
@@ -245,8 +281,8 @@ jobs:
         uses: actions/cache/restore@v5
         with:
           path: .build
-          key: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift.version }}-${{ matrix.macos.version }}-${{ hashFiles('./Package.resolved') }}"
-          restore-keys: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift.version }}-${{ matrix.macos.version }}-"
+          key: "${{ github.event.repository.name }}-integration-tests-${{ matrix.config.mode }}-build-${{ matrix.swift.version }}-${{ matrix.macos.version }}-${{ hashFiles('./Package.resolved') }}"
+          restore-keys: "${{ github.event.repository.name }}-integration-tests-${{ matrix.config.mode }}-build-${{ matrix.swift.version }}-${{ matrix.macos.version }}-"
 
       - name: Build ${{ github.event.repository.name }}
         run: |
@@ -262,19 +298,85 @@ jobs:
         uses: actions/cache/save@v5
         with:
           path: .build
-          key: "${{ github.event.repository.name }}-unit-tests-${{ matrix.config.mode }}-build-${{ matrix.swift.version }}-${{ matrix.macos.version }}-${{ hashFiles('./Package.resolved') }}"
+          key: "${{ github.event.repository.name }}-integration-tests-${{ matrix.config.mode }}-build-${{ matrix.swift.version }}-${{ matrix.macos.version }}-${{ hashFiles('./Package.resolved') }}"
 
-      - name: Run tests
+      - name: Run tests while capturing packets
+        id: tests-run
         run: |
+          sudo tcpdump -w dns.pcap 'port 53 and (host 8.8.4.4 or host 240.1.2.3)' &
+          TCPDUMP_PID=$!
+
+          # Disable 'set -e' to prevent the script from exiting on non-zero exit codes
+          set +e
           swift test \
-            --skip "IntegrationTests." \
+            --filter "IntegrationTests." \
             --skip-build \
-            --enable-code-coverage \
             -Xswiftc -require-explicit-sendable \
             -c ${{ matrix.config.mode }}
+          echo "exit-status=$?" >> $GITHUB_OUTPUT
+          set -e
 
-      - name: Submit code coverage
-        uses: vapor/swift-codecov-action@v0.3
+          kill $TCPDUMP_PID
+
+      - name: Calculate capture file name
+        id: calculate-capture-file-name
+        run: |
+          RESULT="${{ steps.tests-run.outputs.exit-status == 0 && 'success' || 'failure' }}"
+          TIMESTAMP="$(date -u +"%Y-%m-%d-%H-%M-%S")"
+          SHORT_SHA="$(echo '${{ github.sha }}' | cut -c 1-7)"
+          FILE_NAME="swift-dns_dns_capture_${TIMESTAMP}_${RESULT}_${{ matrix.macos.version }}_${{ matrix.swift.version }}_${{ matrix.config.mode }}_${{ matrix.xcode.version }}_${SHORT_SHA}"
+          FILE_NAME="${FILE_NAME//:/_}"
+
+          echo "file_name=${FILE_NAME}" >> "${GITHUB_OUTPUT}"
+
+          mv dns.pcap "${FILE_NAME}.pcap"
+
+      - name: Archive packet capture
+        uses: actions/upload-artifact@v7
         with:
-          build_parameters: "-c ${{ matrix.config.mode }}"
-          codecov_token: "${{ secrets.CODECOV_TOKEN }}"
+          name: "${{ steps.calculate-capture-file-name.outputs.file_name }}"
+          path: "${{ steps.calculate-capture-file-name.outputs.file_name }}.pcap"
+
+      - name: Exit with correct status
+        run: exit ${{ steps.tests-run.outputs.exit-status }}
+
+  android-integration-tests:
+    strategy:
+      fail-fast: false
+      matrix:
+        swift:
+          - version: 6.3
+        config:
+          - mode: "debug"
+          - mode: "release"
+
+    runs-on: ubuntu-latest
+
+    timeout-minutes: 30
+
+    steps:
+      - name: Ensure zstd is available for faster caching
+        run: sudo apt-get update -yq && sudo apt-get install -yq zstd
+
+      - name: Check out code
+        uses: actions/checkout@v7
+        with:
+          persist-credentials: false
+
+      - name: Replace symlinks with the actual files
+        run: find . -type l -exec sh -c 'LINKED="$(readlink -f "{}")"; rm "{}"; cp -a "$LINKED" "{}"' \;
+
+      - name: Run unit tests
+        uses: skiptools/swift-android-action@2044b79660f201ccef8cbce62877e4ec5409f9c8 # v2.9.5
+        with:
+          # Ubuntu runners low on space causes the emulator to fail to install
+          free-disk-space: true
+          android-emulator-test-folder: /data/local/tmp/android-xctest
+          test-env: PROJECT_ROOT_FOR_TESTING=/data/local/tmp/android-xctest
+          swift-version: ${{ matrix.swift.version }}
+          swift-configuration: ${{ matrix.config.mode }}
+          copy-files: Tests
+          swift-build-flags: >-
+            --build-tests
+            --explicit-target-dependency-import-check error
+          swift-test-flags: --filter "IntegrationTests."
